# Generated by Django 5.1.5 on 2025-02-26 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lead_type', models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('renter', 'Renter'), ('landlord', 'Landlord')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
